apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: aws-iam-policies
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/zxwvrblv/aws-iam-policies
  ref:
    branch: main
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: aws-iam-policies
  namespace: flux-system
spec:
  approvePlan: "auto"
  interval: 1m
  path: ./policies
  sourceRef:
    kind: GitRepository
    name: aws-iam-policies
    namespace: flux-system
